version: '3'
services: 
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports: 
      - '5000:5000'
    networks:
      - 'net'
    environment:
      - DATABASE_URL=sqlite:///example.sqlite
      - GEOCODE_API_KEY=add-your-geo-api-key
      - WEATHER_API_KEY=add-your-weather-api-key

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - 'net'
    depends_on:
      - api

networks:
  net:
    driver: bridge
